### ISSUE TITLE
1.B (ex 1.A) corrélation prix blé

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#10]
une visualisation avec deux layouts de positionnement et deux viariables de classement.

## layout:
- réseaux lien de corrélation du prix du blé > 5
- géographique avec fond de carte des bassin versants https://geo.data.gouv.fr/fr/datasets/e5def66126db862118a9db3ad98d4c5209fa6add (/!\ frontière contemporainre... on propose de vivre avec cette distortion)

## variables
- classe de modularité Louvain du réseau
- bassin versant

La viz prend deux paramètres : un layout et une variable

## Données : 
- géolocaliser les villes et nettoyer leur label
- attribuer les villes à leur bassin versants (clipping geographique)
- récupère le geojson des provinces françaises 1789

**Comment by robindemourat** [comment]
Une option très cool d'un point de vue viz (mais pertinente ? cela reste à discuter) serait aussi de rendre possible le basculement entre spatialisation en réseau et spatialisation géo. Ça voudrait dire : 

- en version réseau dessiner les liens entre deux nœuds quand les villes correspondantes sont connectées par un cours d'eau ou une proximité côtière (cela suppose de documenter cela dans une matrice ou d'accéder à un dataset qui le fait déjà, c'est du travail)
- en version carte dessiner les cours d'eau et les côtes (cela suppose d'avoir ça en geojson quelque part)
