### ISSUE TITLE
2.A diversité des produits

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#12]
small multiples par direction des diversité de produits par année des exports
mode de représentation : heatmap horizontal du taux par opacité dans le temps

option : focus visuel sur une année paramétrable 

![IMG_20230406_171223](https://user-images.githubusercontent.com/1876890/230423021-2a2ea639-336c-4dd1-91dc-a613d10e787b.jpg)

**Comment by robindemourat** [comment]
- [ ] idée en option : pour les small multiples représenter des bandes/lignes de rectangles colorés où la saturation/valeur de la couleur représente la concentration ? pour  varier le mode de représentation afin de coder qu'on est pas sur des quantités comme ailleurs

J'aime l'idée du treemap explicatif, ok pour le mettre en option en fonction des autres viz et des ressources

**Comment by robindemourat** [comment]
Modifs : 

- [ ] GD : j’ai fait planter 3 fois assez rapidement le site en jouant avec cette viz (les tool tips n’apparaissaient plus). Il y a peut-être un bug ? [PNS: même problème]

- [ ] Silvia: je propose de mettre la légende en noir et en gras car je l’ai cherchée…et en bulle, la notion de ‘concentration des exports’ me semble assez confuse, il faudra à minima expliquer dans le texte
