### ISSUE TITLE
ABANDON 2.B diversité des secteurs produits/partenaires

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#13]
Enquête n'a pas aboutie. Poursuit-on ?

- [ ] ajouter un calcul herfindhal du commerce par partenaire dans le temps ? 
- [ ] croiser produits/partenaires en comparant un ou deux tops produits dans chaque direction ?

**Comment by robindemourat** [comment]
À discuter en fonction des ressources et du reste du travail à faire. Mais a priori je serais pour abandonner ça, c'est clairement de la continuation d'enquête donc hors du scope de ce post-sprint.
