### ISSUE TITLE
3.A & 3.B Impact de la guerre sur le commerce et la navigation

### ISSUE THREAD

**Issue by robindemourat** [medialab/portic-storymaps-2023#19]
# Impact sur le commerce

<img width="479" alt="Capture d’écran 2023-03-16 à 15 09 59" src="https://user-images.githubusercontent.com/1876890/225643550-111f8fbf-4989-4b90-a4f9-cce7c6e74a98.png">

- [ ] faire un composant qui permet de séectionner colonnes et lignes 
- [ ] (Paul) vérifier l'effet de la disponibilité des données sur la méthode. La tendance est une moyenne des indices de tendances or si on manque de données pour des années particulièrement difficile pour un port mais pas pour l'autre on fausse la comparaison des indices potentiellement largement. -> réduire au dénominateur commun des années qu'on a pour les différents ports comparés

- [ ]  ajouter tendances sur la navigation navigo

# Qui assure le commerce en période de guerre

<img width="491" alt="Capture d’écran 2023-03-16 à 15 24 21" src="https://user-images.githubusercontent.com/1876890/225647586-c6973796-e11c-4da9-b44e-c54be6e18d3c.png">

- [ ] à intégrer avec option stream entre les paires d'année pour signifier l'évolution : 

![IMG_20230407_102316](https://user-images.githubusercontent.com/1876890/230573390-fd96635d-f9d1-4ff3-a975-a8791a99f719.jpg)

- [ ] Attention aux labels 'en guerre' = 'en guerre dans la guerre qui suit'

# Zoom sur le levant

- [ ] carte de la méditerranée avec les ports du levant taille = tonnage cumulé sur la période vers Marseille

Il y a par ailleurs un début d'explication toflit18 :

<img width="632" alt="Capture d’écran 2023-03-16 à 15 13 48" src="https://user-images.githubusercontent.com/1876890/225644522-adfcce97-1f83-430f-a662-3c4e80013b97.png">

- [ ] Série à reprendre telle quelle en l'annotant avec les guerres et passer en part avec représentation du commerce total de Marseille sur la période (barchart + une courbe)

![IMG_20230407_102316](https://user-images.githubusercontent.com/1876890/230573331-3a266510-ddda-41b9-ab35-fa765abd5b71.jpg)

<img width="491" alt="Capture d’écran 2023-03-16 à 15 24 21" src="https://user-images.githubusercontent.com/1876890/225647586-c6973796-e11c-4da9-b44e-c54be6e18d3c.png">

- [ ] on reprend la représentation des répartitions des pavillons en limitant les trajets à ceux partant du levant

![visualization(11)](https://user-images.githubusercontent.com/1876890/230608724-1e0fa914-236c-442e-90f1-8223ee13dad9.png)

**Comment by bmaz** [comment]
Par ailleurs, est-ce qu'on ne comprend pas mieux en montrant simplement l'évolution de la vitesse moyenne ?
![vitesse_moyenne](https://user-images.githubusercontent.com/5666046/228011276-cdf08c68-c7f2-46db-99e0-d96eabd5f317.png)

**Comment by robindemourat** [comment]
Merci @bmaz !

Perso je lis une corrélation possible avec la guerre pour l'Angleterre, et le Nord, rien de probant à première vue pour le reste en effet.

NB méthodo : on a ci-dessus regroupé les pavillons selon la classif partner_grouping, et séparé les français en Ponant et Levant grâce au lieu de naissance du capitaine.

Continuations possibles (je m'assigne dessus) : 

- [ ] explorer vitesse/distance/stagelength/stagesnb en regroupant par guerre/paix/neutre
- [ ] explorer les rapports aux tailles de bateaux avec 3-4 métaclasses : nb_travels/vitesse/distance/stagelength/stagesnb
- [ ] croiser taille avec partner_grouping, guerre
- [ ] faire tout ça en absolu, rapport à la moy totale, rapport à la moy par groupe (pour visualiser variations)

**Comment by robindemourat** [comment]
Sauvegarde issue initiale : 

# Impact sur le commerce

<img width="479" alt="Capture d’écran 2023-03-16 à 15 09 59" src="https://user-images.githubusercontent.com/1876890/225643550-111f8fbf-4989-4b90-a4f9-cce7c6e74a98.png">

- [ ] (Paul) vérifier l'effet de la disponibilité des données sur la méthode. La tendance est une moyenne des indices de tendances or si on manque de données pour des années particulièrement difficile pour un port mais pas pour l'autre on fausse la comparaison des indices potentiellement largement. -> réduire au dénominateur commun des années qu'on a pour les différents ports comparés

- [ ] (Guillaume) regarder avec la même méthode l'effet des guerres sur les indices de Herfindal

Il y a par ailleurs un début d'explication toflit18 :

<img width="632" alt="Capture d’écran 2023-03-16 à 15 13 48" src="https://user-images.githubusercontent.com/1876890/225644522-adfcce97-1f83-430f-a662-3c4e80013b97.png">

- [ ] Série à reprendre telle quelle en l'annotant avec les guerres ?
- [ ] Rapporter à la part du total par année pour mettre en avant la chute du levant ?

# Impact sur la navigation 

Évolution générale : 

<img width="640" alt="Capture d’écran 2023-03-16 à 15 20 48" src="https://user-images.githubusercontent.com/1876890/225646441-a5bf517c-6024-45bc-adc4-5ac36ef7cb38.png">

- [ ] faire une seule viz d'histogrammes en lignes les uns sur les autres (stage_length / milage / tonnages) avec mise en avant des années de guerres

Répartition pavillons : 

<img width="467" alt="Capture d’écran 2023-03-16 à 15 22 38" src="https://user-images.githubusercontent.com/1876890/225647012-2e01ab54-bb08-4c65-845f-9149cdc26856.png">

À faire pour y voir plus clair : 

- [ ] tester normalisation par année

- [ ] tester avec pavillons par classes plus petites (pays du nord / pays méditerranée / français ?)

Répartition des pavillons en fonction du statut : 

<img width="491" alt="Capture d’écran 2023-03-16 à 15 24 21" src="https://user-images.githubusercontent.com/1876890/225647586-c6973796-e11c-4da9-b44e-c54be6e18d3c.png">

Principalement besoin d'analyse / d'un argument ici.

Impact de la guerre sur les vitesses et longueurs des trajets : 

<img width="482" alt="Capture d’écran 2023-03-16 à 15 26 57" src="https://user-images.githubusercontent.com/1876890/225648406-13ba11e9-ccde-414a-a0c6-2f3159871724.png">

- [ ] Refaire avec des paires guerre->paix successives (commentaire de GD )(https://docs.google.com/document/d/1ugq0XHGDPh4BCBU8LBNi6MdshVfLsrLjJvg8528xRD4/edit?pli=1&disco=AAAAsWtHgxs)

- [ ] reprendre les classes neutre/paix/guerre/... pour y voir plus clair 

- [ ] reprendre les stacked bar chart normalisés pour y voir plus clair

**Comment by robindemourat** [comment]
À faire pour finalisation : 

- [ ] GD : “perte mémoire” n’est pas très clair. Mettre “perte” simplement ?
- [ ] en bas, dans “Utiliser les données de la navigation”, mettre ‘Tonnage estimé (Navigocorpus)’ et “Distance (Navigocorpus)’

- [ ] pour Carrière et pour ‘entrées Navigo’ l’échelle indique “v.”: c’est l’abréviation de quoi ? peut-être mieux ‘u.’ pour unités” ou “n’ pour ‘navires ? 
- [ ] ajouter la légende pour la couleur verte (= moyenne de l’estimation du gain en temps de guerre) -> modifier la ligne avec le moins
- [ ] Au début l’affichage dans le storytelling est OK, mais quand ça zoome en descendant sur Marseille -Bordeaux et La Rochelle,  , il y a une superposition gênante à gauche de la légende
![Capture d’écran 2023-08-28 à 15 39 53](https://github.com/medialab/portic-storymaps-2023/assets/1876890/26e8a3fd-d996-4b0a-874b-79c589f17314)
