### ISSUE TITLE
1.C (ex 1.B) part des navigation sud-est vers Marseille

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#21]
Fond de carte des provinces coloré par province centré sud-est Levant avec un point par port du barchart.

en dessous du fond de carte ajout d'un bar chart horizontal avec les parts du nombre de congés des ports du sud-est allant vers Marseille. Ordonné les ports par lattitude.

Option : trait pointillé entre carte et barchart

![IMG_20230406_163502](https://user-images.githubusercontent.com/1876890/230416350-30834d30-2961-4ecb-8906-0e6e28a85c9d.jpg)

**Comment by robindemourat** [comment]
Modifs : 

- [ ] pb bugs de zéro dans infobulles
![Capture d’écran 2023-08-28 à 12 26 33](https://github.com/medialab/portic-storymaps-2023/assets/1876890/f6dcca9d-b629-41d2-896a-431b7d0877c0)
