### ISSUE TITLE
Intro.A Carte Marseille

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#5]
on réutilise le composant carto générique avec deux layers : 
- [ ] cercle taille = commerce total (pour info sauf reexport produit coloniaux)
- [ ] triangle dont la base est le nombre de bateaux et la hauteur le tonnage moyen des bateaux
- [ ] utiliser la classification WAR à reconstruire depuis classification pour Navigo

# Layer 1 toflit18

On reprend le plus possible cette viz : 

![carte-de-paul-co-carte-de-la-valeur-des-importations-et-des-exportations-de-marseille-en-1789-legende](https://user-images.githubusercontent.com/1876890/230723275-06ddbc01-2837-4374-bd7d-08ec87f35379.png)

Décision à prendre :  centrer sur Europe/Afrique du Nord ou sur l'ensemble des points ?

Warnings com de Silvia : 

> Attention: il faut enlever “France” de la carte car les trafics avec la France sont saisis soit en import soit en export et que cela ne sert pas à démontrer le caractère mondial du commerce de Marseille.
Attention: les données de Totlit semblent incomplètes du moins pour le Portugal (pb de saisie ou pb de complétude des sources ????)
A discuter de l’opportunité de laisser les couleurs du déficit étant donné que la redistribution du vert colonial “Monde” vers l’Italie et le Levant changerait la donne et que tout ou presque deviendrait jaune.

- [ ] utiliser balance commerciale hors réexports
- [ ] supprimer la balance et montrer monde
- [ ] mettre un code couleur pour les données manquantes

# Layer 2 navigo

![marseille-en-1789-un-port-international-navigation](https://user-images.githubusercontent.com/1876890/232785818-f2073c49-dc76-459e-bb30-bc6320de1689.png)

- [ ] triangle dont la base est le nombre de bateaux et la hauteur le tonnage (estimé) moyen des bateaux
- [ ] cabotage oui mais on enlève France

**Comment by robindemourat** [comment]
Doutes sur la question des évolutions - je cc mon com:

> j'ai un peu peur des small multiples géolocalisés - d'autant que je vois pas de mention de la dimension diachronique à ce stade dans les contenus non ? si confirmé je serai pour s'en tenir à un snapshot avec 89.

Idée à discuter : je me demande si on ne pourrait pas reprendre les double-triangles imports exports de la partie 3 de La Rochelle ? ou alors les donuts (qui dans la rochelle) représentaient les données toflit18) - [https://medialab.github.io/portic-storymaps-2021/fr/atlas/viz-principale-partie-3](https://www.google.com/url?q=https://medialab.github.io/portic-storymaps-2021/fr/atlas/viz-principale-partie-3&sa=D&source=docs&ust=1678960389660898&usg=AOvVaw3UcYujmcbxXDSmNRFEekrZ)

**Comment by robindemourat** [comment]
- [ ] changer le titre: pays étrangers de départ 
- [ ] bas de la carte mangé chez certains
- [ ] "Serait-il possible de faire partir la flèche vers les “Amériques” à l'horizontale vers la gauche (ça doit aller vers la Guadeloupe et pas vers le cap Horn)"
- [ ] déplacer République de Raguse sur la côte est de l’Adriatique (Raguse = Dubrovnik et pas raguse en Sicile)


Vérif : 

> vérifier que la pêche à Terre-Neuve ne soit pas comprise dans ‘Angleterre’ car ce sont des pêcheurs français et cela ne rentre pas dans la balance du commerce (voir avec Christine au cas où, mais le plus simple serait je pense de enlever de ‘Angleterre’ tous les poincall de départ qui commencent par la lettre “B” (qui caractérise les ports américains, donc Terre-Neuve).

**Comment by robindemourat** [comment]
Modifs sup (pour harmo) : 

- [ ] diviser couleur par source ?
- [ ] mettre flèches en bas de la carte (Afrique & Asie) plus proches de l'élément
