### ISSUE TITLE
Intro.B histo direction de ferme 

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#6]
On fait une carte avec le fond de carte des provinces France.
On réutlise les variables visuels de intro.A pour représenter le commerce (total + balance) et les navigations (sorties/enrées et tonnage moyen).

Données
- [ ] géolocaliser les directions de fermes Toflit18
- [ ] utiliser commerce total
- [ ] supprimer les 149 'relache' pour estimations tonnages Marseille
- [ ] pour Marseille on prends les congés 
- [ ] caculer le tonnage moyen

Questions : 
- pour quoi les tonnages sont ils représentés sur 1787 ? Parce qu'on a les tonnages pour 1787 pour la france

Au final 3 layers: 
- commerce total 1789
- navigation en 1787

![IMG_20230406_114348](https://user-images.githubusercontent.com/1876890/230341456-ba332ff1-ae3a-4310-bd21-f6de801570e2.jpg)

**Comment by robindemourat** [comment]
pour la question de la part du total, j'afficherais la part du commerce total :

1. ou bien avec un stacked barchart jouant sur la couleur (barre crise représentant le commerce colonial au-dessus)

2. ou bien en rajoutant en dessous une rangée normalisée avec des stacked de la même hauteur montrant colonial/autre

**Comment by robindemourat** [comment]
a2ed23114b6b662134f84e0bb8d4e379618b8852 77faaab9a9801f3584a8cb4d2dde678bf2560f91 7a08166619b3c35b40464a2035bd4c6e1b086afa

**Comment by robindemourat** [comment]
Modifs : 

- [ ] il faudrait déplacer “Cap-Français) à l’est de Bordeaux pour éviter la superposition 

Vérif : 

> VERIFIER (avec Christine ???) d’où vient le tonnage du Cap-Français car nous n’avons pas les données !!!!!! (nous ne connaissons que le nombre des congés). Le même problème se pose (si j’augmente le nombre de ports dans l’Atlas) pour tous les ports en Provence et Languedoc où on n’a pas non plus les tonnages

> du coup le tonnage moyen de Marseille me surprend bcp (très élevé) et je pense que c’est le même souci que pour les ports sans données précédents ( l’explication du ‘bon’ procédé dans le texte me semble raisonnable (mais laquelle de deux est représentée?) mais je me demande si c’est bien cela qui est représenté
