### ISSUE TITLE
1.A (ex Intro.C) évolutions commerce top 4 directions de ferme + navigation marseille

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#7]
![evolution-et-croissance-du-commerce-et-de-la-navigation-de-marseille-au-18eme-siecle](https://user-images.githubusercontent.com/1876890/232724903-befc02b5-6623-4b89-835f-eb4d0264ad2f.png)

On reprend le layout de la viz La Rochelle partie 1 à savoir: 

- barchart de la part du commerce total
- line chart evolution total absolu
- on ajoute la courbe de tendance ET l'indicateur de tendance dans la légende

On représente : 
- Total France
- Total Marseille
- Total Bordeaux
- Total Rouen 
- Total Nantes
- navigation (congés) Marseille sans le barchart (scale différente)

Questions: 
Quelle série utiliser pour évolution navigation ? => congés

Données : 
- tendance sur navigation à calculer

![IMG_20230406_121828(1)](https://user-images.githubusercontent.com/1876890/230351504-8cfc9892-a1c2-4693-9d5b-26a16f32139d.jpg)

**Comment by robindemourat** [comment]
- [ ] renommer cette issue en 1.A quand acté (cascade sur les actuels 1.A et 1.B)

- modèle : line chart avec points de données et pas de ligne quand série incomplète, ou barcharts en petits multiples (mais pas avec toutes) ?

Sur la question des parts :

- +1 pour passer en part et ajouter une courbe du total france uniquement

- OU on pourrait s'inspirer de la viz 1 de La Rochelle (en plus simple) - https://medialab.github.io/portic-storymaps-2021/fr/atlas/viz-principale-partie-1 - ça implique de choisir 1 ou 2 DF pour comparaison


Qu'en penses-tu ?

**Comment by robindemourat** [comment]
Voici mes deux remarques/questionnements concernant le passage de cette viz en v1 : 

- [ ] interrogation sur la syntaxe du caller concernant les "rows" ([ici](https://github.com/medialab/portic-storymaps-2023/blob/main/src/visualizations/1_A/index.js#L17)) - est-ce qu'il ne faut pas un `JSON.parse` ou quelque chose dans le style ?
- [ ]  je pense qu'il manque au niveau des légendes une indication de ce qu'est la ligne des régressions sur les graphiques. Est-ce que ça ne pourrait pas être un cartel centré sur la ligne de "part des exports fr" et  "valeur absolue des exports", de la même couleur que la ligne de régression, indiquant le pourcentage de croissance (qui est actuellement dans le titre) - e.g. "+3.2%/an (régression)" ? Qu'en-penses-tu ?

**Comment by robindemourat** [comment]
Modifs : 

- [ ] PNS: sur les visus “dynamisme du commerce des principales directions de ferme”, en descendant, sur mon écran les dates du graphique de La Rochelle ne sont pas totalement visibles (la fin de l’écran les coupe).
