### ISSUE TITLE
[à fermer car redondante avec #7 ?] Intro.C tendance de croissance

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#8]
- [ ] signifier quels points sont utilisés pour la régression
- [ ] réduire/interactif le nombre de direction ?
- [ ] réduire/interactif le nombre de variables colonial/total-import-export ?

**Comment by robindemourat** [comment]
- [ ] renommer cette issue en 1.A quand acté (cascade sur les actuels 1.A et 1.B)

Il faut discuter de comment transformer cette viz en quelque chose de démonstratif, en l'état c'est très dur à lire. Outre les points listés ci-dessus auxquels je souscris quelques idées complémentaires : 

- [ ] optionnellement n'afficher que les régressions pour pouvoir superposer plusieurs localités
- [ ] penser tout l'appareil d'annotation nécessaire pour rendre compréhensible le principe des régression et la métrique de croissance
- [ ] tbc
