### ISSUE TITLE
Intro.C evolution navigation

### ISSUE THREAD

**Issue by paulgirard** [medialab/portic-storymaps-2023#9]
- [ ] calculer le même indicateur de tendance de croissance et comparer à ceux imports/exports (déjà fait je crois dans la partie guerre)
- [ ] unifier vocabulaire entrées/dépositions sorties/congés ?
- [ ] unifier modèle visuel

**Comment by robindemourat** [comment]
- [ ] renommer cette issue en 1.A quand acté (cascade sur les actuels 1.A et 1.B)

- [ ] modèle en petits multiples "foldables" en fonction de l'argumentation - croisé avec #8  ?
